# Generated by Django 6.0 on 2025-12-31 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الكورس')),
                ('description', models.TextField(verbose_name='وصف الكورس')),
                ('image', models.ImageField(upload_to='course_images/', verbose_name='صورة الغلاف')),
            ],
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود التفعيل')),
                ('is_used', models.BooleanField(default=False, verbose_name='هل تم استخدامه؟')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='courses_mohamed.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
                ('video_url', models.URLField(verbose_name='رابط الفيديو')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses_mohamed.course')),
            ],
        ),
    ]
