# Generated by Django 6.0 on 2025-12-31 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_mohamed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب الدرس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course_images/', verbose_name='صورة الكورس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الكورس'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses_mohamed.course', verbose_name='الكورس'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(verbose_name='رابط الفيديو (YouTube/Vimeo)'),
        ),
        migrations.DeleteModel(
            name='ActivationCode',
        ),
    ]
